REM   Script: Ex1C
REM    

CREATE TABLE STUDENT 
( 
    ROLLNO INTEGER PRIMARY KEY, 
    SNAME VARCHAR(20) NOT NULL, 
    PASSPORT_NUMBER INTEGER, 
    DEPT_CODE INTEGER NOT NULL, 
    AGE INTEGER NOT NULL, 
    CGPA NUMBER(2, 1), 
    CLUB_ID INTEGER 
);

INSERT INTO STUDENT VALUES(1, 'ABC', 123, 1, 18, 8.5, 232);

INSERT INTO STUDENT VALUES(2, 'DEF', 456, 2, 18, 9.5, 233);

INSERT INTO STUDENT VALUES(3, 'GHI', 789, 3, 18, 7.5, 234);

SELECT * FROM STUDENT;

SELECT ROLLNO, SNAME AS STUDNAME FROM STUDENT;

UPDATE STUDENT SET CGPA = 8.9 WHERE ROLLNO = 1;

SELECT CGPA+0.5 AS CGPACHANGED FROM STUDENT WHERE CGPA = 5.9 OR CGPA = 6.9 OR CGPA = 7.9 OR CGPA = 8.9;

INSERT INTO STUDENT VALUES(4, 'MNO', 124, 1, 18, 7.5, 235);

INSERT INTO STUDENT VALUES(5, 'PQi', 125, 1, 18, 8.9, 236);

INSERT INTO STUDENT VALUES(6, 'MNOPQRi', 127, 1, 18, 6.5, 237);

SELECT * FROM STUDENT WHERE (SNAME LIKE 'M____%i' OR SNAME LIKE 'V____%i');

SELECT * FROM STUDENT WHERE (SNAME LIKE '_a%') OR (SNAME LIKE '%A%') OR (SNAME LIKE '%a%') OR (SNAME LIKE '%E%') OR (SNAME LIKE '%e%') OR (SNAME LIKE '%I%') OR (SNAME LIKE '%i%') OR (SNAME LIKE '%O%') OR (SNAME LIKE '%o%') OR (SNAME LIKE '%U%') OR (SNAME LIKE '%u%');

INSERT INTO STUDENT VALUES(7, 'QPR', 128, 1, 18, 7.5, 238);

INSERT INTO STUDENT VALUES(8, 'ZBC', 129, 1, 18, 9.5, 239);

SELECT ROLLNO, SNAME FROM STUDENT WHERE (SNAME NOT LIKE 'Z%') AND (SNAME NOT LIKE 'Q%');

UPDATE STUDENT SET PASSPORT_NUMBER = NULL WHERE ROLLNO = 1 OR ROLLNO = 3 OR  ROLLNO = 5 OR ROLLNO = 7;

SELECT * FROM STUDENT;

SELECT SNAME FROM STUDENT WHERE PASSPORT_NUMBER IS NULL ORDER BY SNAME ASC;

UPDATE STUDENT SET CLUB_ID = NULL WHERE ROLLNO = 2 OR ROLLNO = 4 OR ROLLNO = 6 OR ROLLNO = 8;

SELECT * FROM STUDENT;

SELECT ROLLNO, SNAME FROM STUDENT WHERE CLUB_ID IS NOT NULL;

ALTER TABLE STUDENT ADD(PART_TIME_STUDENT INTEGER, PART_TIME_EMPLOYEE INTEGER, FULL_TIME_STUDENT INTEGER);

UPDATE STUDENT SET PART_TIME_STUDENT = 1, PART_TIME_EMPLOYEE = 0, FULL_TIME_STUDENT = 0 WHERE ROLLNO = 1 OR ROLLNO = 3 OR ROLLNO = 5 OR ROLLNO = 7;

UPDATE STUDENT SET PART_TIME_STUDENT = 0, PART_TIME_EMPLOYEE = 1, FULL_TIME_STUDENT = 0 WHERE ROLLNO = 2 OR ROLLNO = 4;

UPDATE STUDENT SET PART_TIME_STUDENT = 0, PART_TIME_EMPLOYEE = 0, FULL_TIME_STUDENT = 1 WHERE ROLLNO = 6 OR ROLLNO = 8 ;

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD(SID INTEGER, PHONE_NUMBER INTEGER);

UPDATE STUDENT SET SID = ROLLNO;

SELECT * FROM STUDENT;

UPDATE STUDENT SET PHONE_NUMBER = 1234567890 WHERE ROLLNO = 1;

UPDATE STUDENT SET PHONE_NUMBER = 2234567890 WHERE ROLLNO = 2;

UPDATE STUDENT SET PHONE_NUMBER = 3234567890 WHERE ROLLNO = 3;

UPDATE STUDENT SET PHONE_NUMBER = 4234567890 WHERE ROLLNO = 4;

SELECT * FROM STUDENT;

CREATE TABLE STUDENT_PARTTIMESTUDY AS SELECT SID, SNAME, PHONE_NUMBER FROM STUDENT WHERE PART_TIME_STUDENT = 1;

SELECT * FROM STUDENT_PARTTIMESTUDY;

CREATE TABLE STUDENT_PARTTIMEEMP AS SELECT SID, SNAME, PHONE_NUMBER FROM STUDENT WHERE PART_TIME_EMPLOYEE = 1;

SELECT * FROM STUDENT_PARTTIMEEMP;

CREATE TABLE STUDENT_FULLTIMESTUDY AS SELECT SID, SNAME, PHONE_NUMBER FROM STUDENT WHERE FULL_TIME_STUDENT = 1;

SELECT * FROM STUDENT_FULLTIMESTUDY;

SELECT MAX(CGPA) AS MAX_CGPA, MIN(CGPA) AS MIN_CGPA, AVG(CGPA) AS AVG_CGPA FROM STUDENT;

SELECT COUNT(*) AS TOT_STUD FROM STUDENT;

UPDATE STUDENT SET AGE = 19 WHERE ROLLNO = 2;

UPDATE STUDENT SET AGE = 20 WHERE ROLLNO = 3;

UPDATE STUDENT SET AGE = 21 WHERE ROLLNO = 4;

SELECT * FROM STUDENT;

SELECT SUM(COUNT(DISTINCT AGE)) AS AGE_UNIQUE FROM STUDENT GROUP BY AGE HAVING COUNT(AGE) = 1;

SELECT SUM(AGE) AS AGE_SUM FROM STUDENT;

SELECT DEPT_CODE, COUNT(DEPT_CODE) AS COUNT FROM STUDENT GROUP BY DEPT_CODE;

SELECT DEPT_CODE, AVG(CGPA) AS CGPA_AVG FROM STUDENT GROUP BY DEPT_CODE;

ALTER TABLE STUDENT ADD(DEPT_NAME VARCHAR(20));

UPDATE STUDENT SET DEPT_NAME = 'IT' WHERE DEPT_CODE = 1;

UPDATE STUDENT SET DEPT_NAME = 'ECE' WHERE DEPT_CODE = 2;

UPDATE STUDENT SET DEPT_NAME = 'CSE' WHERE DEPT_CODE = 3;

SELECT * FROM STUDENT;

SELECT AVG(CGPA) AS CGPA_AVG_IT FROM STUDENT WHERE DEPT_NAME = 'IT';

SELECT DEPT_NAME, COUNT(*) AS COUNT FROM STUDENT GROUP BY DEPT_NAME HAVING COUNT(*) > 4;

SELECT * FROM STUDENT_PARTTIMESTUDY ;

SELECT * FROM STUDENT_PARTTIMEEMP ;

SELECT * FROM STUDENT_FULLTIMESTUDY;

INSERT INTO STUDENT_FULLTIMESTUDY VALUES(4, 'MNO', 4234567890);

SELECT * FROM STUDENT_FULLTIMESTUDY;

SELECT SNAME FROM STUDENT_FULLTIMESTUDY INTERSECT SELECT SNAME FROM STUDENT_PARTTIMEEMP;

INSERT INTO STUDENT_PARTTIMEEMP VALUES(7, 'QPR', NULL);

SELECT * FROM STUDENT_PARTTIMEEMP;

SELECT SNAME FROM STUDENT_PARTTIMESTUDY MINUS SELECT SNAME FROM STUDENT_PARTTIMEEMP;

SELECT SNAME FROM STUDENT_PARTTIMESTUDY UNION SELECT SNAME FROM STUDENT_PARTTIMEEMP;

