Script: Ex1B   

CREATE TABLE STUDENT(  
    ROLLNO INTEGER PRIMARY KEY,   
    SNAME VARCHAR(20),   
    PASSPORT_NUMBER INTEGER UNIQUE,   
    DEPT_CODE INTEGER,   
    AGE INTEGER,   
    QUALIFICATION VARCHAR(20),   
    CONSTRAINT CHK_STUDENT CHECK(AGE > 17 AND AGE < 21)  
);

ALTER TABLE STUDENT MODIFY QUALIFICATION VARCHAR(20) DEFAULT 'HSC';

INSERT INTO STUDENT VALUES(1, 'ABC', 2011, 1, 19, 'BTECH');

INSERT INTO STUDENT VALUES(3, 'GHI', 2013, 3, 19, 'BE');

INSERT INTO STUDENT (ROLLNO, SNAME, PASSPORT_NUMBER, DEPT_CODE, AGE) VALUES(2, 'DEF', 2012, 1, 19);

SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES(1, 'ABC', 2011, 1, 19, 'BTECH');

INSERT INTO STUDENT VALUES(4, 'ABC', 2011, 1, 19, 'BTECH');

INSERT INTO STUDENT VALUES(5, 'ABC', 2011, 1, 25, 'BTECH');

CREATE TABLE STUD_MARKS  
(  
    SROLLNO INTEGER,  
    ROLLNO INTEGER,  
    SEMNO INTEGER,  
    GPA NUMBER(3, 2),  
    CGPA NUMBER(3, 2),  
    PRIMARY KEY(ROLLNO),  
    FOREIGN KEY(SROLLNO)  
    REFERENCES STUDENT(ROLLNO)  
);

INSERT INTO STUD_MARKS VALUES(1, 1, 3, 9.87, 9.73);

DELETE FROM STUDENT WHERE ROLLNO = 1;

CREATE TABLE DEPARTMENT 
( 
    DEPT_NAME VARCHAR(20) NOT NULL,  
    DEPT_CODE INTEGER NOT NULL,  
    HOD_NAME VARCHAR(20) NOT NULL,  
    LOCATION_ VARCHAR(20) NOT NULL 
);

SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT VALUES('IT', 1, 'ABC', 'E-BLOCK');

INSERT INTO DEPARTMENT VALUES('ECE', 1, 'DEF', 'F-BLOCK');

INSERT INTO DEPARTMENT VALUES('CSE', 3, 'GHI', 'G-BLOCK');

SELECT * FROM DEPARTMENT;

DELETE FROM DEPARTMENT WHERE DEPT_CODE = 1;

SELECT * FROM DEPARTMENT;

SELECT * FROM STUDENT;

SELECT * FROM STUD_MARKS;

SELECT * FROM DEPARTMENT;

TRUNCATE TABLE STUD_MARKS;
TRUNCATE TABLE STUDENT;


TRUNCATE TABLE DEPARTMENT


SELECT * FROM STUDENT;

SELECT * FROM STUD_MARKS;

SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_CODE);

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT FOREIGN KEY(DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE) ON DELETE CASCADE;

INSERT INTO DEPARTMENT VALUES('IT', 1, 'ABC', 'E-BLOCK');

INSERT INTO DEPARTMENT VALUES('ECE', 2, 'DEF', 'F-BLOCK');

SELECT * FROM DEPARTMENT;

INSERT INTO STUDENT VALUES(1, 'ABC', 2011, 1, 19, 'BTECH');

INSERT INTO STUDENT VALUES(2, 'DEF', 2012, 2, 18, 'BE');

SELECT * FROM STUDENT;

DELETE FROM DEPARTMENT WHERE DEPT_CODE = 1;

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT


TRUNCATE TABLE DEPARTMENT


ALTER TABLE STUDENT DROP CONSTRAINT FK_STUDENT;

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT FOREIGN KEY(DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE) ON DELETE SET NULL;

SELECT * FROM STUDENT;

SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT VALUES('IT', 1, 'ABC', 'E-BLOCK');

INSERT INTO DEPARTMENT VALUES('ECE', 2, 'DEF', 'F-BLOCK');

SELECT * FROM DEPARTMENT;

INSERT INTO STUDENT VALUES(1, 'ABC', 2011, 1, 19, 'BTECH');

INSERT INTO STUDENT VALUES(2, 'DEF', 2012, 2, 18, 'BE');

SELECT * FROM STUDENT;

DELETE FROM DEPARTMENT WHERE DEPT_CODE = 1;

SELECT * FROM STUDENT;

ALTER TABLE STUDENT MODIFY DEPT_CODE INTEGER DEFAULT NULL;

ALTER TABLE STUDENT MODIFY SNAME VARCHAR(20) NOT NULL;

ALTER TABLE STUDENT MODIFY SNAME VARCHAR(20) NULL;

