REM   Script: Ex1A
REM    

CREATE TABLE STUDENT(ROLLNO NUMBER(2, 0), SNAME VARCHAR(15), ADDRESS VARCHAR(20), CGPA NUMBER(5,2));

DESC STUDENT


ALTER TABLE STUDENT MODIFY(ROLLNO NUMBER(3, 0));

DESC STUDENT


ALTER TABLE STUDENT ADD(DEPARTMENT VARCHAR(20), CLUB_MEMBERSHIP_ID INTEGER, DATE_OF_BIRTH DATE);

DESC STUDENT


ALTER TABLE STUDENT DROP COLUMN ADDRESS;

DESC STUDENT


ALTER TABLE STUDENT RENAME COLUMN DATE_OF_BIRTH TO DOB;

DESC STUDENT


INSERT INTO STUDENT VALUES(1, 'ABC', 9.839, 'ITG1', 2003, '03-AUG-03');

INSERT INTO STUDENT VALUES(2, 'DEF', 9.839, 'ITG1', 2004, '08-AUG-04');

INSERT INTO STUDENT(ROLLNO, SNAME, CGPA, DEPARTMENT, DOB) VALUES(3, 'GHI', 9.849, 'ITG1', '06-AUG-03');

SELECT * FROM STUDENT;

UPDATE STUDENT SET ROLLNO=6 WHERE ROLLNO = 1;

UPDATE STUDENT SET ROLLNO=8 WHERE ROLLNO = 2;

UPDATE STUDENT SET ROLLNO=11 WHERE ROLLNO = 3;

SELECT * FROM STUDENT;

UPDATE STUDENT SET CGPA = 10 WHERE ROLLNO = 6;

ALTER TABLE STUDENT ADD(ADDRESS VARCHAR(20));

DESC STUDENT


UPDATE STUDENT SET ADDRESS = 'CBE' WHERE ROLLNO = 6;

UPDATE STUDENT SET ADDRESS = 'TIR' WHERE ROLLNO = 8;

UPDATE STUDENT SET ADDRESS = 'KAR' WHERE ROLLNO = 11;

SELECT * FROM STUDENT;

SELECT SNAME, ADDRESS FROM STUDENT WHERE ROLLNO > 10;

UPDATE STUDENT SET SNAME = 'RAM', CGPA = 8.5 WHERE ROLLNO = 8;

SELECT * FROM STUDENT WHERE CGPA >= 8.5 AND SNAME = 'RAM' OR SNAME = 'RAVI';

UPDATE STUDENT SET ADDRESS = 'CHENNAI' WHERE ROLLNO = 8;

SELECT ADDRESS FROM STUDENT WHERE ROLLNO != 5 AND ADDRESS = 'CHENNAI';

CREATE TABLE STUDENT_COPY AS SELECT * FROM STUDENT;

SELECT * FROM STUDENT_COPY;

CREATE TABLE STUDENT_CGPA AS SELECT ROLLNO, CGPA FROM STUDENT;

SELECT * FROM STUDENT_CGPA;

CREATE TABLE PARTTIME_STUDENT AS SELECT * FROM STUDENT WHERE 1 = 0;

SELECT * FROM PARTTIME_STUDENT;

DESC PARTTIME_STUDENT


ALTER TABLE STUDENT ADD(PARTTIME INTEGER);

UPDATE STUDENT SET PARTTIME = 1 WHERE ROLLNO = 6;

UPDATE STUDENT SET PARTTIME = 0 WHERE ROLLNO = 8;

UPDATE STUDENT SET PARTTIME = 1 WHERE ROLLNO = 11;

SELECT * FROM STUDENT;

INSERT INTO PARTTIME_STUDENT SELECT ROLLNO, SNAME, CGPA, DEPARTMENT, CLUB_MEMBERSHIP_ID, DOB, ADDRESS FROM STUDENT WHERE PARTTIME = 1;

SELECT * FROM PARTTIME_STUDENT;

ALTER TABLE STUDENT READ ONLY;

ALTER TABLE STUDENT READ ONLY;

SELECT * FROM STUDENT;

DELETE FROM STUDENT WHERE ROLLNO = 6;

ALTER TABLE STUDENT READ WRITE;

DELETE FROM STUDENT WHERE ROLLNO = 6;

TRUNCATE TABLE STUDENT


SELECT * FROM STUDENT;

DROP TABLE STUDENT;

DESC STUDENT


